"""image picture

Revision ID: 183b834aaa2b
Revises: cbdc8d38253e
Create Date: 2022-06-17 19:45:12.380316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183b834aaa2b'
down_revision = 'cbdc8d38253e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.String(length=128), nullable=True))
    op.drop_column('users', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('users', 'image')
    # ### end Alembic commands ###
