"""remove UserPicture

Revision ID: 1a35165e1172
Revises: 183b834aaa2b
Create Date: 2022-06-18 00:58:53.318887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a35165e1172'
down_revision = '183b834aaa2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_picture',
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mimetype', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_picture_user_id_fkey'),
    sa.PrimaryKeyConstraint('width', 'height', 'user_id', name='users_picture_pkey')
    )
    # ### end Alembic commands ###
