"""cancel_at_period_end

Revision ID: 1a7d5e1ccc5b
Revises: 98103bd093b0
Create Date: 2022-07-14 08:58:32.514236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7d5e1ccc5b'
down_revision = '98103bd093b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_data', sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stripe_data', 'cancel_at_period_end')
    # ### end Alembic commands ###
    