"""cancel_at_period_end

Revision ID: 23f67feb4eec
Revises: 6c017f63f9da
Create Date: 2022-07-14 11:14:29.534602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f67feb4eec'
down_revision = '6c017f63f9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    