"""add stripe_customer row to model user

Revision ID: 257707a0e922
Revises: 085558f8ce5e
Create Date: 2022-06-29 14:21:26.416381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257707a0e922'
down_revision = '085558f8ce5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_customer')
    # ### end Alembic commands ###
