"""<message>

Revision ID: 27a44329559d
Revises: 79c4834b2631
Create Date: 2022-08-05 12:32:50.699046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a44329559d'
down_revision = '79c4834b2631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('answers_limit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'answers_limit')
    # ### end Alembic commands ###
    