"""Subscription

Revision ID: 2a7ea3225dcd
Revises: 4ce80d91b430
Create Date: 2022-07-14 14:42:46.123020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a7ea3225dcd'
down_revision = '4ce80d91b430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('Basic', 'Advance', name='subscriptiontype'), nullable=True),
    sa.Column('customer_id', sa.String(length=512), nullable=True),
    sa.Column('session_id', sa.String(length=512), nullable=True),
    sa.Column('cancel_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('subscription_id', sa.String(length=512), nullable=True),
    sa.Column('product_id', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stripe_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.VARCHAR(length=628), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=628), autoincrement=False, nullable=True),
    sa.Column('subscription', postgresql.ENUM('Basic', 'Advance', name='subscriptiontype'), autoincrement=False, nullable=True),
    sa.Column('subscription_id', sa.VARCHAR(length=628), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.VARCHAR(length=628), autoincrement=False, nullable=True),
    sa.Column('cancel_at_period_end', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='stripe_data_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stripe_data_pkey')
    )
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
    