"""cancel_at_period_end nullable = True

Revision ID: 4ce80d91b430
Revises: 23f67feb4eec
Create Date: 2022-07-14 11:26:01.674614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce80d91b430'
down_revision = '23f67feb4eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    