"""add_session_model

Revision ID: 55c3922f1d0f
Revises: de2ea2072af6
Create Date: 2022-06-30 15:48:54.253052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c3922f1d0f'
down_revision = 'de2ea2072af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp_session_start', sa.DateTime(), nullable=True),
    sa.Column('timestamp_session_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('answers', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answers', 'sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'session_id')
    op.drop_table('sessions')
    # ### end Alembic commands ###
