"""successful_message

Revision ID: 61bdb6334b77
Revises: 93d141bed0d0
Create Date: 2022-07-04 16:26:05.116430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61bdb6334b77'
down_revision = '93d141bed0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('successful_message', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'successful_message')
    # ### end Alembic commands ###
