"""add stripe column to model user 

Revision ID: 6532de3070b4
Revises: 257707a0e922
Create Date: 2022-06-29 17:18:58.863642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6532de3070b4'
down_revision = '257707a0e922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_id', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_id')
    # ### end Alembic commands ###
