"""Subscription modify

Revision ID: 6548c0f10c86
Revises: 2a7ea3225dcd
Create Date: 2022-07-14 14:45:30.928414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6548c0f10c86'
down_revision = '2a7ea3225dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    