"""customer_id

Revision ID: 6c017f63f9da
Revises: 1a7d5e1ccc5b
Create Date: 2022-07-14 09:48:28.878336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c017f63f9da'
down_revision = '1a7d5e1ccc5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    