"""user role

Revision ID: 72bad138f77a
Revises: 1a08dece2369
Create Date: 2022-06-17 16:05:33.752798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bad138f77a'
down_revision = '1a08dece2369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
