"""db  modify

Revision ID: 79c4834b2631
Revises: 6548c0f10c86
Create Date: 2022-07-14 14:48:23.491162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c4834b2631'
down_revision = '6548c0f10c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    