"""session

Revision ID: 8392f62378ff
Revises: 61bdb6334b77
Create Date: 2022-07-05 20:09:28.723857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8392f62378ff'
down_revision = '61bdb6334b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'session',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_constraint('sessions_session_key', 'sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sessions_session_key', 'sessions', ['session'])
    op.alter_column('sessions', 'session',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
