"""question

Revision ID: 904665cd990a
Revises: edd41060d314
Create Date: 2022-06-22 02:24:04.646743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904665cd990a'
down_revision = 'edd41060d314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
