"""questions in survey

Revision ID: 93d141bed0d0
Revises: fdc0d1856471
Create Date: 2022-07-04 08:04:18.963539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d141bed0d0'
down_revision = 'fdc0d1856471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
