"""answers in question model

Revision ID: a0454c7d4d21
Revises: cd8b8616eca4
Create Date: 2022-07-03 20:08:59.625376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0454c7d4d21'
down_revision = 'cd8b8616eca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
