"""add ids for google and facebook to User

Revision ID: a78fb5038fe9
Revises: 5b2951d22846
Create Date: 2022-06-10 15:16:16.059464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78fb5038fe9'
down_revision = '5b2951d22846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('facebook_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'facebook_id')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
