"""add stripe session id

Revision ID: ad5dd92e3abd
Revises: 6532de3070b4
Create Date: 2022-06-29 17:25:40.005189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5dd92e3abd'
down_revision = '6532de3070b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_session_id', sa.String(length=256), nullable=True))
    op.drop_column('users', 'session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('users', 'stripe_session_id')
    # ### end Alembic commands ###
