"""add uuid

Revision ID: b160c795bec3
Revises: 883945643403
Create Date: 2022-06-27 09:29:54.526742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b160c795bec3'
down_revision = '883945643403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('uuid', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'uuid')
    # ### end Alembic commands ###
