"""session

Revision ID: bc1ca8c5a32e
Revises: d57bc0222de5
Create Date: 2022-07-12 18:24:01.702885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1ca8c5a32e'
down_revision = 'd57bc0222de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
