"""change_models_stripe_sessions

Revision ID: cd8b8616eca4
Revises: 55c3922f1d0f
Create Date: 2022-07-01 12:33:59.416343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8b8616eca4'
down_revision = '55c3922f1d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('session', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'sessions', ['session'])
    op.drop_constraint('sessions_user_id_fkey', 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'user_id')
    op.add_column('stripe_data', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('stripe_data', sa.Column('customer_id', sa.String(length=256), nullable=True))
    op.add_column('stripe_data', sa.Column('session_id', sa.String(length=256), nullable=True))
    op.add_column('stripe_data', sa.Column('product_id', sa.String(length=256), nullable=True))
    op.create_foreign_key(None, 'stripe_data', 'users', ['user_id'], ['id'])
    op.drop_column('stripe_data', 'stripe_session_id')
    op.drop_column('stripe_data', 'stripe_customer_id')
    op.drop_constraint('users_stripe_data_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'stripe_data_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_data_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_stripe_data_id_fkey', 'users', 'stripe_data', ['stripe_data_id'], ['id'])
    op.add_column('stripe_data', sa.Column('stripe_customer_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('stripe_data', sa.Column('stripe_session_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stripe_data', type_='foreignkey')
    op.drop_column('stripe_data', 'product_id')
    op.drop_column('stripe_data', 'session_id')
    op.drop_column('stripe_data', 'customer_id')
    op.drop_column('stripe_data', 'user_id')
    op.add_column('sessions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sessions_user_id_fkey', 'sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_column('sessions', 'session')
    # ### end Alembic commands ###
