"""stripe model

Revision ID: d9865ed70b9f
Revises: a0454c7d4d21
Create Date: 2022-07-03 22:30:04.440596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9865ed70b9f'
down_revision = 'a0454c7d4d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
