"""add_stripe_model

Revision ID: de2ea2072af6
Revises: fbc4f22e65dd
Create Date: 2022-06-30 11:56:24.300431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de2ea2072af6'
down_revision = 'fbc4f22e65dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=256), nullable=True),
    sa.Column('stripe_session_id', sa.String(length=256), nullable=True),
    sa.Column('subscription', sa.Enum('Basic', 'Advance', name='subscriptiontype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('stripe_data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'stripe_data', ['stripe_data_id'], ['id'])
    op.drop_column('users', 'subscription')
    op.drop_column('users', 'stripe_session_id')
    op.drop_column('users', 'stripe_customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('stripe_session_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('subscription', postgresql.ENUM('Basic', 'Advance', name='subscription'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'stripe_data_id')
    op.drop_table('stripe_data')
    # ### end Alembic commands ###
