"""refresh model

Revision ID: ef32d14e9b4a
Revises: b160c795bec3
Create Date: 2022-06-27 15:28:20.745034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef32d14e9b4a'
down_revision = 'b160c795bec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
