"""session date

Revision ID: efb6012b6815
Revises: 6c86eeb58d2c
Create Date: 2022-07-07 11:34:51.760299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb6012b6815'
down_revision = '6c86eeb58d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
