"""delete from user model full name

Revision ID: f69d59fa14b0
Revises: e2409776ae70
Create Date: 2022-06-21 14:20:29.834210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69d59fa14b0'
down_revision = 'e2409776ae70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
