"""subscription

Revision ID: fbc4f22e65dd
Revises: ad5dd92e3abd
Create Date: 2022-06-29 19:13:26.299073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc4f22e65dd'
down_revision = 'ad5dd92e3abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
