"""subscription_id

Revision ID: fdc0d1856471
Revises: d9865ed70b9f
Create Date: 2022-07-03 23:49:20.535301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc0d1856471'
down_revision = 'd9865ed70b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_data', sa.Column('subscription_id', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stripe_data', 'subscription_id')
    # ### end Alembic commands ###
